model_name = "llama3"
flavor = "debugmodel"
tokenizer_name = "common-pile/comma-v0.1-2t"

# job 
job_name = "test-munin-7b-open-pt"
wandb_project = "munin-7b-open-pt"
enable_wandb = false

# parallelism
num_nodes = 1
data_parallel_shard_degree = 8
data_parallel_replicate_degree = 1

# training settings
train_batch_size = 8
seq_len = 4096
train_num_steps = 1000
scheduler = "linear_warmup_constant_sqrt_decay"
warmup_steps = 100
cooldown_steps = 100
checkpoint_interval = 1000
compile = true
enable_cut_cross_entropy = false
ac_mode = "none"
selective_ac_option = "op"

[dataset]
bos_token = 2
eos_token = 1
data_dirs = [
    "/work/production/data/dsk-open-dyna-0-of-1-cp-0-of-16-train/",
]
dataset_weights = "1.0"

[opt_cfg] # must specify *all* fields here, will not merge with defaults
lr = 1e-5
betas = [0.9, 0.95]
weight_decay = 0.1
eps = 1e-9
fused = true
